#!/usr/bin/python   
import logging
import globvars as gv
from crontab import CronTab
from datetime import datetime
 
LXP = "LH > "
APP = "AP > "

def parse_message(topic, payload):
    #         0         1   2   3    4      5     6
    # 66619478619276L/user/led/dim/device/0x01/onboardled   payload
	message = topic.split("/")
	device  = message[4]
	subtype = message[3]
	edtype  = message[2]
	user    = message[1]
	payld   = payload.split(":")
	args    = payld[0]

	cmd = 0
	msg = 0
	arg = 0
	ad1 = 0
	ad2 = 0
	ad3 = 0
	ad4 = 0
	grp = 0
	lnk = 0
	typ = 0
	ack = 0
	add = 0

    #ACK es el ultimo elemento del mensaje. Si hay mas de una opcion se asume debe venir
    #  ON:ACK   
    #  OFF:NOACK  
    #  50:ARG1:ARG2:ACK  
	payldsize = len(payld)
	if  payldsize > 1:
		withack = payld[payldsize-1]
		if withack == "ACK":
			ack = 1

	if  edtype != "system":

		command = message[6]
		if gv.tipoED.has_key(edtype):
				typ = gv.tipoED[edtype]
		else:
			return "DeviceNotSupported"

		action  = command.rstrip()    

    ###################################################################################################
		if device == "device":
			lnk = int(message[5],0)
			cmd=0x11 #Send_ByID

		elif device == "group":
			grp = int(message[5])
			cmd=0x12 #Send_ByGroup

		#Comandos comunes para todos los tipos de LED
		if edtype == "led":

            #power ON/OFF  - compatible entre dimming y ON/OFF
			if  action == "power":
				msg=0x40 #Power

			elif action == "setgroup":
				cmd=0x20  #SET_GROUP
				msg=0x20  #SET_GROUP
				grp=int(args,0)  # Debe llegar - 0x0001
				
			elif action == "onboardled":
				
				if args == "ON":
					msg=0xA1 
				elif args == "OFF":
					msg=0xA0
				elif args == "TOGGLE":
					msg=0xA3	
				else:
					return "MessageNotRecognized"

			elif action == "dimming":

				if subtype == "dim":
					msg=0x50 #DIM_PWM
					arg=int(payld[0])
				else:
					return "CommandNotSupported"
			else:
				return "CommandNotRecognized"
		else:
				return "DeviceNotSupported"

	###################################################################################
	# ---------------- System Messages ------------------
	else:
		if message[3]=="config":
			if message[5]=="request":
				cmd=0x81
			else:
				return "CommandNotRecognized"
		if message[3]=="rule":
			if message[4]=="cron" and message[5]=="add":
				logging.info("%sRule Added",LXP)

				## Agregaremos aqui el tipo 
				cron   = CronTab()
				dt = datetime.now()

				#cron.write_to_user( user='bob' )
				#MIN:HR:DOM:MON:DOW:CMD
				logging.debug("%sRule Received: %s",LXP,payld)
				cron_job = "/usr/bin/mosquitto_pub -h localhost -t " + gv.lh + "/" + payld[5] + " -m \"" + payld[6] +"\""
				logging.debug("%sCMD: %s",LXP,cron_job)
				job  = cron.new(command=cron_job, comment='Generated by:'+ user + ', on: ' + dt.strftime('%Y/%m/%d %H:%M:%S'))
				job.setall(payld[0], payld[1], payld[2], payld[3],payld[4])
				job.enable()
				cron.write()

			else:
				return "CommandNotRecognized"
		else:
			return "CommandNotRecognized"
	#Mensaje de sistema

	cmd2ap =  "I|0x%02X|0x%02X|0x%02X|0x%02X,0x%02X,0x%02X,0x%02X|0x%02X|0x%04X|0x%02X|%d|%02d|U" % (cmd,msg,arg,ad1,ad2,ad3,ad4,lnk,grp,typ,ack,add)

	return cmd2ap
